### ISSUE TITLE
Call for Speakers

### ISSUE THREAD

**Issue by xeodou** [jsconfcn/ShenJS#14]
Our Call for Speakers is open from now! With the growing crowd joining us for the biggest Javascript event in China, we are excited to hear from you what you would like to do speak about! Contact us and send us your proposal centred around Javascript at large here to join us and make an awesome event.

**Comment by xeodou** [comment]
ref #9 

My name is Matt Ma. I am the author of ember-rocks.

ember-rocks is a web's scaffolding tool for building ambitious modern web application just like Yeoman. It uses ES6 module loader system to wire up the client side code, which utilized Ember.js MVC framework. User could quickly start a project, write future ES6 code, pre-compile to vanilla ES5 code in development time via Babel, renamed from [6to5] project. There are lots of other cool features, click here to read more,

Server side framework currently uses Express, but I am trying to migrate into Koa, (see the progress here) when io.js reaches its stabilizing releases (production ready stage).

There are lots of topics related to it that I could talk about, for example, Ember.js, which is not popular in China yet, but oppositely, it is pretty successful in US. Isomorphic javascript, Cordova or PhoneGap integration etc. If interested, ping me for more details.

**Comment by fengmk2** [comment]
+1 for @mattma

**Comment by mattma** [comment]
Thanks for the intro, @xeodou 

This talk is an brief introduction of very popular MVC client side javascript framework, Ember.js. 

Ember is not well-known in China due to the fact that they are run and maintained by its awesome contributors from the community, a group of javascript enthusiasts. Every core member work on Ember for Free. Well, it is not technically FREE. Company who bet big on Ember hire them in a big way. 

Ember is not backed by Google, Facebook, or any big companies at all. We have seen some bad examples when any open source project is lead by one corporation. Angular 2.0 is one of them. The corporation could completely kill the project even though Angular has 53% of market share as of end of 2014. They JUST DO NOT CARE about the community/eco-system but revenue (Do not kill me for that). In addition, io.js is the recent fork of Node.js project with its awesome Open Governance model against big company "half" open source restriction modal. This list will go on and on.

If you look at the company who use Ember, there are a long promising list of companies are betting big on Ember, like Yahoo (2 billion dollars Ad revenue scaled on Ember), Netflix, Square, Groupon, etc. [Ember 2.0](https://github.com/emberjs/rfcs/pull/15) is announced almost the same time when Angular 2.0 is out. It takes backward compatibilities seriously. Your application should  have an easy migration to the 2.0 release. In short, if your app run fine in the current version of Ember 1.10.0, it should just work out of the box in Ember 2.0. Other than that, Ember is going to change its two way data binding to unidirectional data flow (Like Facebook Flux), virtual DOM with diffing algorithm(Like React), drop controller concept and move with component onwards(Like Angular), isomorphic way running app on both server side and client side(Like Meteor), and more. Ember roll out its new features every 6 weeks using Chrome 6 weeks release model. All features are requested by the community and YOU. If you want to get your voice heard, check out [here](https://github.com/emberjs/rfcs) 

To get started with Ember development, I will definitely show you about [ember-rocks](https://github.com/mattma/ember-rocks). How you could build your Ember app in a breeze! One of the essential build tool to start your next Ember project. Then use **ember-rocks** to collaborate with your teammates, build your production-ready code, mobile-ready via cordova, and so on. It let you focus on the logic of your application, without even worrying about naming convention, file location, etc, thanks to the "convention over configuration" highly opinionated _Ember way is the highway_ model. Sometimes, it turns out that is not a bad thing.

**Comment by xeodou** [comment]
Hi @mattma 
 Thanks for your commit, we are plan to invite some guys give a speech about the frontend javascript frameworks (Angularjs, Reacts, Emberjs etc.), we want jsconf China  not only focus on backend, we want  people talking some new technology  in both in backend and frontend. We will consider your topic, and we will email you  when have a decision.

**Comment by bencrox** [comment]
I am developing a meteor js front-end adapter with influxdb support. Not sure can hurry up for the event.

**Comment by mattma** [comment]
@xeodou Javascript is everywhere! Thanks! I am looking forward hearing from you.

**Comment by xeodou** [comment]
Hi @bencrox 
meteorjs is a good point we can thinking this before if we can get some meteorjs core member have a speech.

**Comment by bencrox** [comment]
@xeodou the tap-18n package dev is working in HK. I can pull him in. 
There are also some i-Beacon startups using Meteor to do front end in HK.
I use meteor to do Asterisk PaBX user interface.

**Comment by zensh** [comment]
@dead-horse 会来讲 koa 吗？或者有谁会要讲 koa？如果没有，我就自荐一个：

# 《koa 和 toa 的框架原理及开发实践》

About me:

https://github.com/zensh 

https://www.teambition.com/info/member?index=9

My open source work:

https://github.com/teambition

https://github.com/thunks

https://github.com/toajs

[toa](https://github.com/toajs/toa) 是在 koa 基础上修改的 server 框架，使用非常相似，但有两个根本性的区别和其他一些细小区别：
1. toa 不支持（抛弃了）级联 `yield *next`；
2. toa 推崇模块式（而非中间件式）开发。

目前基于 toa 开发的社区系统已经在线上运行 https://bbs.teambition.com/ ，完善后可能会开源出来。

内容：
1. koa 的框架结构和编程范式
2. JS异步编程基础：promise、thunk、generator
3. koa 的异步组合原理和 toa 的异步组合原理
4. koa / toa 强大的异常处理机制
5. koa / toa 中间件和模块的开发讲解
6. 一个 server 实例的讲解

**Comment by hax** [comment]
I'd like to give a speech, but can not decide the topic now ^_^  , maybe after qcon beijing (April) .

**Comment by thoward** [comment]
I think we need to formalize the CFP process a bit before we go much further.

We should create a page on the site with a embedded form and instructions. State the purpose of the conference, the closing date of the CFP, what kinds of talks we're looking for, etc. 

I've done this in the past with Google Docs, so all CFP submissions go into a spreadsheet. Finally, at the end, use a voting process among the organizers to determine which talks are accepted. 

This will make the conference much more fair and inclusive.

**Comment by quentinberder** [comment]
Sounds like a good idea, this would be a small iteration in the website.

**Comment by quentinberder** [comment]
We should take inspiration:

http://2015.cssconf.com/call-for-speakers/

**Comment by diysimon** [comment]
Hi, @xeodou , I am the leader of baidu EFE team.
Are you interested in data visualization, my team can share lots of cool things about ECharts, ECharts-X（http://echarts.baidu.com/x/doc/example/map3d_flights.html）, webGL, Canvas and so on.

And we also have many excellent open-source product and experiences in mobile, Nodejs, Front-end framework and development platform which you can know more in http://efe.baidu.com and https://github.com/ecomfe

I really hope that we can have the opportunity to share our experiences in the past 3 years.

Thank you so much.

**Comment by xeodou** [comment]
Hi @diysimon 

Thank you for your commit, ECharts project is a great open source project. I have a look before. And we are glad if we can have a talk about  data visualization .  But we are starting working the  _Call For Speaker_ page.  Currently github issue is not a good place to manager the topic and speakers. We will let you know when we have finish this stuff.

Best

**Comment by bencrox** [comment]
So with @diysimon leading baidu EFE , any other big brother coming out ?

**Comment by fraserxu** [comment]
@bencrox Where're the Tencent folks, haven't heard any thing from them yet. :(

**Comment by bencrox** [comment]
@fraserxu no worry. I thought you guys in SZ/China have better connection. Anyway I can help to reach out if that speeds up.

**Comment by fraserxu** [comment]
We're based in Shanghai. Yes no worry for now, they'll be there.

**Comment by mattma** [comment]
I will represent for **Walmart** & **WalmartLabs** & **Walmart E-Commence**, US Engineering Headquarter, if my talk has been picked. Cheers!

**Comment by undoZen** [comment]
我愿意分享我在 CreditCloud 这一年多来做 Frontend DevOps 的一些工程化相关的经验，不过具体内容还不是很确定。

**Comment by sskyy** [comment]
自荐  

# Gilgamesh: 支付宝控制台类产品中的前端最佳实践

关于我: 
- [http://www.cnblogs.com/sskyy](http://www.cnblogs.com/sskyy)
- [https://github.com/sskyy](https://github.com/sskyy)

作品:
- http://twentyjs.com
- https://github.com/sskyy/Gilgamesh
- https://github.com/sskyy/zero
- todo.zerojs.io

自荐内容简介:  
支付宝有很多控制台类型的产品。Gilgamesh 是支付宝在这类型的产品探索中沉淀出的一系列工具的集合。这里先简单介绍两个它解决的问题:
- 控制台类产品组件化程度高，复用频繁。但在不同场景下复用组件时，常常要求对组件的样式进行细微的调整，例如去掉组件的某个部分等。常规做法是修改组件，提供一些配置项来满足这些需求。但随着业务的发展，甚至外部团队对组件的引用，遇到的场景会越来越多，不可能对所有场景中的需求提供人力支持。Gilgamesh定义了一个新的组件开发规则，能在不修改组件的情况下，实现在"使用时"对组件进行动态修改的能力。
- 控制台类产品的前端数据层相对较重，数据结构和逻辑的复用场景也多。在Angular类的框架中，scope与组件的html结构是耦合的，不适合用来做数据层的载体。Gilgamesh 提供了一个能无缝对接RESTful接口的数据层，并将继续加入事件系统等等高级工具完善前端架构。

以上的两个常见的问题其实不只在控制台类产品中遇到，随着现在前端页面越来越应用化，绝大多数产品都会碰到这样的问题。希望 Gilgamesh 的解决之道能供大家借鉴。

**Comment by plrthink** [comment]
+1 for @diysimon

**Comment by fraserxu** [comment]
@mattma @fengmk2 @bencrox @zensh @hax @thoward @diysimon @undoZen @sskyy @plrthink We just finished the call-for-speaker page here http://2015.jsconf.cn/call-for-speakers-en/

Can you guys help to send your proposal from there? Thanks!

**Comment by fengmk2** [comment]
I think github issues here is more open place and also can let people see these proposals and vote for them.

**Comment by undoZen** [comment]
I agree with @fengmk2

**Comment by fraserxu** [comment]
I agree that github issue is more open, but as @thoward pointed our above

> I think we need to formalize the CFP process a bit before we go much further.

Having a separate page could make the process more standard and easy to manage. The current approach to have it in on github issue is making it a mess(having proposal and votes everywhere).

As for votes, the form tool([jinshuju](https://jinshuju.net/)) we are using for gathering the proposals result support this well. We can open the proposals result easily if we want(they have option to share the result to public or password protected through a link or export as Excel file).

I have contacted the jinshuju team([thoughtworks](http://www.thoughtworks.com/)) yesterday and they are very open and happy to support us, they've already give us a pro account so that we could add more function to the form(custom style, file upload, etc)

In the end when we have all the proposals, we could open another vote form with it, and have the others to vote(this could not be done easily with github issue IMO)

cc/ @fengmk2 @undoZen @thoward

**Comment by fengmk2** [comment]
I'm OK now. @fraserxu your points sound good to me.

**Comment by dfguo** [comment]
I just submitted a topic "React.js at Strikingly" through the form. I will be sharing how we wrote the new generation of Strikingly editor using React.js. The topic will cover how we use React.js + Flux, pre-rendering, immutable.js and testing.

**Comment by clonn** [comment]
:+1:  agree @fengmk2

**Comment by hax** [comment]
@fraserxu I've already submit the topic _JavaScript: The World's Best Programming Language_  :smile_cat: 

The title is parody of DC's famous _JavaScript: The World's Most Misunderstood Programming Language_. But no joking, I really think JS has evolved and become the best programming language (except some special areas such as system programming). I'd like to share my view and thought about it — what changes of the language and the community in past 15 years, and how these changes impact the future.

Of course this will be a controversial subject, but **it's not about victory, it's all about attitude (我就是认真) :sweat_smile:** .

**Comment by fraserxu** [comment]
Love it! Controversial topic could make the conference more interesting! :D (Personal view)

**Comment by zensh** [comment]
@xeodou 我需要更新一下话题描述：

`目前基于 toa 开发的社区系统已经在线上运行 https://bbs.teambition.com/ ，完善后可能会开源出来。` =>

`目前 Teambition 的用户社区、文件服务和消息服务均基于 toa 开发。`

**Comment by xeodou** [comment]
好的，我一会帮你改。

Xeodou

Twitter: @xeodou https://twitter.com/xeodou
Github: xeodou https://github.com/xeodou

**Comment by xeodou** [comment]
@zensh 我帮你改好了

**Comment by DottiP** [comment]
Greetings everyone! Our experienced devs in Shenzhen are very interested in participating this event and become a speaker, is it possible for us to send the topics/ details over via email as there will be a few to choose from :)  Also would love to speak to someone about the sponsorship too.  Thank you so much guys!

**Comment by quentinberder** [comment]
@DottiP thanks for reaching out.  You can come and discuss directly with us in our Slack channel: https://shenjs.herokuapp.com/, this will make things easier.

**Comment by fraserxu** [comment]
@DottiP You can also send us an email to claire@wiredcraft.com or fraserxu@wiredcraft.com if you prefer an email.

**Comment by DottiP** [comment]
Fantastic!  Thank you so much both of you :)  Is there any special topics that the event wants to emphasize on?? I will definitely submit via email, thanks Fraser!

**Comment by fraserxu** [comment]
@DottiP We do have a list of topics in mind for the conference in [this list](https://github.com/jsconfcn/ShenJS/issues/18), but since it's been a while for now, and other speakers may have submit their topics yet, you'd better check our speaker voter page for the existing topics first. https://jinshuju.net/f/Dfys92

Please take your time and send your proposal to me as soon as possible. Thanks.

**Comment by DottiP** [comment]
Appreciated!  Thank you so much team!

**Comment by quentinberder** [comment]
Call is closed now, speakers have been chosen by the community and announced on the site http://2015.jsconf.cn/ . Closing.
