### ISSUE TITLE
Logo and Branding Design

### ISSUE THREAD

**Issue by thoward** [jsconfcn/ShenJS#17]
I'd like to revisit the logo/branding. I don't see where the design process happened for this, and I'm not personally very satisfied with what we have right now. 

My criticisms are: 
- The logo looks like a GUI window, which doesn't make any sense for JavaScript, since it's either embedded in browser, or on a server, or on a hardware device.. but almost never used to make native GUI apps.
- The shade of blue we're using seems juvenile. I'd like to see a more sophisticated color palette. 

Is there something about ShenZhen, that creates a particular character for the city, that we could incorporate into the design? Using a city-scape seems like a short-cut. Maybe just use a particular unique building instead of the entire city scape? An interesting historical figure? What is ShenZhen known for, culturally?

**Comment by fraserxu** [comment]
@thoward Shenzhen is one of the **Special Economic Zone** in China, which has developed very fast since the great leader Deng Xiaoping draw a cirle for it, and there's even a song for this.

And now Shenzhen is also known to the world for its (cheap)hardware manufacturing, and also lots of hardware startups(JDI, seeedstudio...). 

For it's location, it's to the south of China and close to Hongkong, which also make lots of sense because it brings advantage and opportunity that make a lot of differences.

**Comment by bencrox** [comment]
JS can be the front end , and now JS can be the back end.
SZ has HouHai ( back sea ) , and now SZ is building QianHai ( front sea ) 

Hmm

**Comment by quentinberder** [comment]
Done, closing.
